export const ActionTypes = {
  SET_PRODUCTS: "SET_PRODUCTS",
  SET_CURRENT_USER: "SET_CURRENT_USER",
  SELECTED_PRODUCT: "SELECTED_PRODUCT",
  REMOVE_SELECTED_PRODUCT: "REMOVE_SELECTED_PRODUCT",
  SET_PRODUCT_STORE: "SET_PRODUCT_STORE",
};